//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50401.0
// 
namespace CompiledDomainModel.Demo.SLFeedReader.FeedReaderService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/MyDomainModel.Wcf")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.DomainObjectBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.FeedItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.FeedCollection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Feed))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Comment))]
    public partial class Item : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.ChildItemCollectionRef ChildrenField;
        
        private System.Guid ItemIDField;
        
        private string ItemLanguageField;
        
        private string ItemNameField;
        
        private string ItemPathField;
        
        private int ItemVersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.ChildItemCollectionRef Children {
            get {
                return this.ChildrenField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildrenField, value) != true)) {
                    this.ChildrenField = value;
                    this.RaisePropertyChanged("Children");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ItemID {
            get {
                return this.ItemIDField;
            }
            set {
                if ((this.ItemIDField.Equals(value) != true)) {
                    this.ItemIDField = value;
                    this.RaisePropertyChanged("ItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemLanguage {
            get {
                return this.ItemLanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemLanguageField, value) != true)) {
                    this.ItemLanguageField = value;
                    this.RaisePropertyChanged("ItemLanguage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemPath {
            get {
                return this.ItemPathField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemPathField, value) != true)) {
                    this.ItemPathField = value;
                    this.RaisePropertyChanged("ItemPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemVersion {
            get {
                return this.ItemVersionField;
            }
            set {
                if ((this.ItemVersionField.Equals(value) != true)) {
                    this.ItemVersionField = value;
                    this.RaisePropertyChanged("ItemVersion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChildItemCollectionRef", Namespace="http://schemas.datacontract.org/2004/07/MyDomainModel.Wcf")]
    public partial class ChildItemCollectionRef : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid ParentIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DomainObjectBase", Namespace="http://schemas.datacontract.org/2004/07/MyDomainModel.Wcf")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.FeedItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.FeedCollection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Feed))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Comment))]
    public partial class DomainObjectBase : CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FeedItem", Namespace="http://schemas.datacontract.org/2004/07/MyDomainModel.Wcf")]
    public partial class FeedItem : CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.DomainObjectBase {
        
        private string DescriptionField;
        
        private string LinkField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FeedCollection", Namespace="http://schemas.datacontract.org/2004/07/MyDomainModel.Wcf")]
    public partial class FeedCollection : CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.DomainObjectBase {
        
        private bool RemoveOldItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RemoveOldItems {
            get {
                return this.RemoveOldItemsField;
            }
            set {
                if ((this.RemoveOldItemsField.Equals(value) != true)) {
                    this.RemoveOldItemsField = value;
                    this.RaisePropertyChanged("RemoveOldItems");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Feed", Namespace="http://schemas.datacontract.org/2004/07/MyDomainModel.Wcf")]
    public partial class Feed : CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.DomainObjectBase {
        
        private string NameField;
        
        private string UrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comment", Namespace="http://schemas.datacontract.org/2004/07/MyDomainModel.Wcf")]
    public partial class Comment : CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.DomainObjectBase {
        
        private CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.ItemRef FeedItemField;
        
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.ItemRef FeedItem {
            get {
                return this.FeedItemField;
            }
            set {
                if ((object.ReferenceEquals(this.FeedItemField, value) != true)) {
                    this.FeedItemField = value;
                    this.RaisePropertyChanged("FeedItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemRef", Namespace="http://schemas.datacontract.org/2004/07/MyDomainModel.Wcf")]
    public partial class ItemRef : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid ReferenceIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ReferenceId {
            get {
                return this.ReferenceIdField;
            }
            set {
                if ((this.ReferenceIdField.Equals(value) != true)) {
                    this.ReferenceIdField = value;
                    this.RaisePropertyChanged("ReferenceId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FixedPaths", Namespace="http://schemas.datacontract.org/2004/07/MyDomainModel.Wcf")]
    public partial class FixedPaths : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item ContentField;
        
        private CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item Content_CommentsField;
        
        private CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.FeedCollection Content_FeedsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item Content_Comments {
            get {
                return this.Content_CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.Content_CommentsField, value) != true)) {
                    this.Content_CommentsField = value;
                    this.RaisePropertyChanged("Content_Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.FeedCollection Content_Feeds {
            get {
                return this.Content_FeedsField;
            }
            set {
                if ((object.ReferenceEquals(this.Content_FeedsField, value) != true)) {
                    this.Content_FeedsField = value;
                    this.RaisePropertyChanged("Content_Feeds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FeedReaderService.SitecoreService")]
    public interface SitecoreService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SitecoreService/GetItemById", ReplyAction="http://tempuri.org/SitecoreService/GetItemByIdResponse")]
        System.IAsyncResult BeginGetItemById(System.Guid itemId, System.AsyncCallback callback, object asyncState);
        
        CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item EndGetItemById(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SitecoreService/GetItemByPath", ReplyAction="http://tempuri.org/SitecoreService/GetItemByPathResponse")]
        System.IAsyncResult BeginGetItemByPath(string itemPath, System.AsyncCallback callback, object asyncState);
        
        CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item EndGetItemByPath(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SitecoreService/GetRootItem", ReplyAction="http://tempuri.org/SitecoreService/GetRootItemResponse")]
        System.IAsyncResult BeginGetRootItem(System.AsyncCallback callback, object asyncState);
        
        CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item EndGetRootItem(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SitecoreService/GetItemsByIds", ReplyAction="http://tempuri.org/SitecoreService/GetItemsByIdsResponse")]
        System.IAsyncResult BeginGetItemsByIds(System.Collections.ObjectModel.ObservableCollection<System.Guid> itemIds, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item> EndGetItemsByIds(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SitecoreService/SelectItems", ReplyAction="http://tempuri.org/SitecoreService/SelectItemsResponse")]
        System.IAsyncResult BeginSelectItems(string query, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item> EndSelectItems(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SitecoreService/SelectSingleItem", ReplyAction="http://tempuri.org/SitecoreService/SelectSingleItemResponse")]
        System.IAsyncResult BeginSelectSingleItem(string query, System.AsyncCallback callback, object asyncState);
        
        CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item EndSelectSingleItem(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SitecoreService/SelectItemsUsingXPath", ReplyAction="http://tempuri.org/SitecoreService/SelectItemsUsingXPathResponse")]
        System.IAsyncResult BeginSelectItemsUsingXPath(string query, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item> EndSelectItemsUsingXPath(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SitecoreService/SelectSingleItemUsingXPath", ReplyAction="http://tempuri.org/SitecoreService/SelectSingleItemUsingXPathResponse")]
        System.IAsyncResult BeginSelectSingleItemUsingXPath(string query, System.AsyncCallback callback, object asyncState);
        
        CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item EndSelectSingleItemUsingXPath(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SitecoreService/GetChildren", ReplyAction="http://tempuri.org/SitecoreService/GetChildrenResponse")]
        System.IAsyncResult BeginGetChildren(System.Guid parentItemId, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item> EndGetChildren(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SitecoreService/CreateItem", ReplyAction="http://tempuri.org/SitecoreService/CreateItemResponse")]
        System.IAsyncResult BeginCreateItem(System.Guid parentItemId, CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item newItem, System.AsyncCallback callback, object asyncState);
        
        CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item EndCreateItem(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SitecoreService/UpdateItem", ReplyAction="http://tempuri.org/SitecoreService/UpdateItemResponse")]
        System.IAsyncResult BeginUpdateItem(CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item item, System.AsyncCallback callback, object asyncState);
        
        void EndUpdateItem(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SitecoreService/DeleteItem", ReplyAction="http://tempuri.org/SitecoreService/DeleteItemResponse")]
        System.IAsyncResult BeginDeleteItem(CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item item, System.AsyncCallback callback, object asyncState);
        
        void EndDeleteItem(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SitecoreService/GetFixedPaths", ReplyAction="http://tempuri.org/SitecoreService/GetFixedPathsResponse")]
        System.IAsyncResult BeginGetFixedPaths(System.AsyncCallback callback, object asyncState);
        
        CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.FixedPaths EndGetFixedPaths(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SitecoreService/RefreshFeed", ReplyAction="http://tempuri.org/SitecoreService/RefreshFeedResponse")]
        System.IAsyncResult BeginRefreshFeed(CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Feed feed, System.AsyncCallback callback, object asyncState);
        
        void EndRefreshFeed(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SitecoreServiceChannel : CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetItemByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetItemByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetItemByPathCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetItemByPathCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetRootItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetRootItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetItemsByIdsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetItemsByIdsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SelectItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SelectItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SelectSingleItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SelectSingleItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SelectItemsUsingXPathCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SelectItemsUsingXPathCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SelectSingleItemUsingXPathCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SelectSingleItemUsingXPathCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetChildrenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetChildrenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetFixedPathsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetFixedPathsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.FixedPaths Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.FixedPaths)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SitecoreServiceClient : System.ServiceModel.ClientBase<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService>, CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService {
        
        private BeginOperationDelegate onBeginGetItemByIdDelegate;
        
        private EndOperationDelegate onEndGetItemByIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetItemByIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetItemByPathDelegate;
        
        private EndOperationDelegate onEndGetItemByPathDelegate;
        
        private System.Threading.SendOrPostCallback onGetItemByPathCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetRootItemDelegate;
        
        private EndOperationDelegate onEndGetRootItemDelegate;
        
        private System.Threading.SendOrPostCallback onGetRootItemCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetItemsByIdsDelegate;
        
        private EndOperationDelegate onEndGetItemsByIdsDelegate;
        
        private System.Threading.SendOrPostCallback onGetItemsByIdsCompletedDelegate;
        
        private BeginOperationDelegate onBeginSelectItemsDelegate;
        
        private EndOperationDelegate onEndSelectItemsDelegate;
        
        private System.Threading.SendOrPostCallback onSelectItemsCompletedDelegate;
        
        private BeginOperationDelegate onBeginSelectSingleItemDelegate;
        
        private EndOperationDelegate onEndSelectSingleItemDelegate;
        
        private System.Threading.SendOrPostCallback onSelectSingleItemCompletedDelegate;
        
        private BeginOperationDelegate onBeginSelectItemsUsingXPathDelegate;
        
        private EndOperationDelegate onEndSelectItemsUsingXPathDelegate;
        
        private System.Threading.SendOrPostCallback onSelectItemsUsingXPathCompletedDelegate;
        
        private BeginOperationDelegate onBeginSelectSingleItemUsingXPathDelegate;
        
        private EndOperationDelegate onEndSelectSingleItemUsingXPathDelegate;
        
        private System.Threading.SendOrPostCallback onSelectSingleItemUsingXPathCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetChildrenDelegate;
        
        private EndOperationDelegate onEndGetChildrenDelegate;
        
        private System.Threading.SendOrPostCallback onGetChildrenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreateItemDelegate;
        
        private EndOperationDelegate onEndCreateItemDelegate;
        
        private System.Threading.SendOrPostCallback onCreateItemCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateItemDelegate;
        
        private EndOperationDelegate onEndUpdateItemDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateItemCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteItemDelegate;
        
        private EndOperationDelegate onEndDeleteItemDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteItemCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetFixedPathsDelegate;
        
        private EndOperationDelegate onEndGetFixedPathsDelegate;
        
        private System.Threading.SendOrPostCallback onGetFixedPathsCompletedDelegate;
        
        private BeginOperationDelegate onBeginRefreshFeedDelegate;
        
        private EndOperationDelegate onEndRefreshFeedDelegate;
        
        private System.Threading.SendOrPostCallback onRefreshFeedCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public SitecoreServiceClient() {
        }
        
        public SitecoreServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SitecoreServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SitecoreServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SitecoreServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetItemByIdCompletedEventArgs> GetItemByIdCompleted;
        
        public event System.EventHandler<GetItemByPathCompletedEventArgs> GetItemByPathCompleted;
        
        public event System.EventHandler<GetRootItemCompletedEventArgs> GetRootItemCompleted;
        
        public event System.EventHandler<GetItemsByIdsCompletedEventArgs> GetItemsByIdsCompleted;
        
        public event System.EventHandler<SelectItemsCompletedEventArgs> SelectItemsCompleted;
        
        public event System.EventHandler<SelectSingleItemCompletedEventArgs> SelectSingleItemCompleted;
        
        public event System.EventHandler<SelectItemsUsingXPathCompletedEventArgs> SelectItemsUsingXPathCompleted;
        
        public event System.EventHandler<SelectSingleItemUsingXPathCompletedEventArgs> SelectSingleItemUsingXPathCompleted;
        
        public event System.EventHandler<GetChildrenCompletedEventArgs> GetChildrenCompleted;
        
        public event System.EventHandler<CreateItemCompletedEventArgs> CreateItemCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> UpdateItemCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteItemCompleted;
        
        public event System.EventHandler<GetFixedPathsCompletedEventArgs> GetFixedPathsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> RefreshFeedCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService.BeginGetItemById(System.Guid itemId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetItemById(itemId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService.EndGetItemById(System.IAsyncResult result) {
            return base.Channel.EndGetItemById(result);
        }
        
        private System.IAsyncResult OnBeginGetItemById(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid itemId = ((System.Guid)(inValues[0]));
            return ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService)(this)).BeginGetItemById(itemId, callback, asyncState);
        }
        
        private object[] OnEndGetItemById(System.IAsyncResult result) {
            CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item retVal = ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService)(this)).EndGetItemById(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetItemByIdCompleted(object state) {
            if ((this.GetItemByIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetItemByIdCompleted(this, new GetItemByIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetItemByIdAsync(System.Guid itemId) {
            this.GetItemByIdAsync(itemId, null);
        }
        
        public void GetItemByIdAsync(System.Guid itemId, object userState) {
            if ((this.onBeginGetItemByIdDelegate == null)) {
                this.onBeginGetItemByIdDelegate = new BeginOperationDelegate(this.OnBeginGetItemById);
            }
            if ((this.onEndGetItemByIdDelegate == null)) {
                this.onEndGetItemByIdDelegate = new EndOperationDelegate(this.OnEndGetItemById);
            }
            if ((this.onGetItemByIdCompletedDelegate == null)) {
                this.onGetItemByIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetItemByIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetItemByIdDelegate, new object[] {
                        itemId}, this.onEndGetItemByIdDelegate, this.onGetItemByIdCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService.BeginGetItemByPath(string itemPath, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetItemByPath(itemPath, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService.EndGetItemByPath(System.IAsyncResult result) {
            return base.Channel.EndGetItemByPath(result);
        }
        
        private System.IAsyncResult OnBeginGetItemByPath(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string itemPath = ((string)(inValues[0]));
            return ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService)(this)).BeginGetItemByPath(itemPath, callback, asyncState);
        }
        
        private object[] OnEndGetItemByPath(System.IAsyncResult result) {
            CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item retVal = ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService)(this)).EndGetItemByPath(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetItemByPathCompleted(object state) {
            if ((this.GetItemByPathCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetItemByPathCompleted(this, new GetItemByPathCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetItemByPathAsync(string itemPath) {
            this.GetItemByPathAsync(itemPath, null);
        }
        
        public void GetItemByPathAsync(string itemPath, object userState) {
            if ((this.onBeginGetItemByPathDelegate == null)) {
                this.onBeginGetItemByPathDelegate = new BeginOperationDelegate(this.OnBeginGetItemByPath);
            }
            if ((this.onEndGetItemByPathDelegate == null)) {
                this.onEndGetItemByPathDelegate = new EndOperationDelegate(this.OnEndGetItemByPath);
            }
            if ((this.onGetItemByPathCompletedDelegate == null)) {
                this.onGetItemByPathCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetItemByPathCompleted);
            }
            base.InvokeAsync(this.onBeginGetItemByPathDelegate, new object[] {
                        itemPath}, this.onEndGetItemByPathDelegate, this.onGetItemByPathCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService.BeginGetRootItem(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetRootItem(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService.EndGetRootItem(System.IAsyncResult result) {
            return base.Channel.EndGetRootItem(result);
        }
        
        private System.IAsyncResult OnBeginGetRootItem(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService)(this)).BeginGetRootItem(callback, asyncState);
        }
        
        private object[] OnEndGetRootItem(System.IAsyncResult result) {
            CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item retVal = ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService)(this)).EndGetRootItem(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetRootItemCompleted(object state) {
            if ((this.GetRootItemCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetRootItemCompleted(this, new GetRootItemCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetRootItemAsync() {
            this.GetRootItemAsync(null);
        }
        
        public void GetRootItemAsync(object userState) {
            if ((this.onBeginGetRootItemDelegate == null)) {
                this.onBeginGetRootItemDelegate = new BeginOperationDelegate(this.OnBeginGetRootItem);
            }
            if ((this.onEndGetRootItemDelegate == null)) {
                this.onEndGetRootItemDelegate = new EndOperationDelegate(this.OnEndGetRootItem);
            }
            if ((this.onGetRootItemCompletedDelegate == null)) {
                this.onGetRootItemCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetRootItemCompleted);
            }
            base.InvokeAsync(this.onBeginGetRootItemDelegate, null, this.onEndGetRootItemDelegate, this.onGetRootItemCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService.BeginGetItemsByIds(System.Collections.ObjectModel.ObservableCollection<System.Guid> itemIds, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetItemsByIds(itemIds, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item> CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService.EndGetItemsByIds(System.IAsyncResult result) {
            return base.Channel.EndGetItemsByIds(result);
        }
        
        private System.IAsyncResult OnBeginGetItemsByIds(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Collections.ObjectModel.ObservableCollection<System.Guid> itemIds = ((System.Collections.ObjectModel.ObservableCollection<System.Guid>)(inValues[0]));
            return ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService)(this)).BeginGetItemsByIds(itemIds, callback, asyncState);
        }
        
        private object[] OnEndGetItemsByIds(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item> retVal = ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService)(this)).EndGetItemsByIds(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetItemsByIdsCompleted(object state) {
            if ((this.GetItemsByIdsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetItemsByIdsCompleted(this, new GetItemsByIdsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetItemsByIdsAsync(System.Collections.ObjectModel.ObservableCollection<System.Guid> itemIds) {
            this.GetItemsByIdsAsync(itemIds, null);
        }
        
        public void GetItemsByIdsAsync(System.Collections.ObjectModel.ObservableCollection<System.Guid> itemIds, object userState) {
            if ((this.onBeginGetItemsByIdsDelegate == null)) {
                this.onBeginGetItemsByIdsDelegate = new BeginOperationDelegate(this.OnBeginGetItemsByIds);
            }
            if ((this.onEndGetItemsByIdsDelegate == null)) {
                this.onEndGetItemsByIdsDelegate = new EndOperationDelegate(this.OnEndGetItemsByIds);
            }
            if ((this.onGetItemsByIdsCompletedDelegate == null)) {
                this.onGetItemsByIdsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetItemsByIdsCompleted);
            }
            base.InvokeAsync(this.onBeginGetItemsByIdsDelegate, new object[] {
                        itemIds}, this.onEndGetItemsByIdsDelegate, this.onGetItemsByIdsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService.BeginSelectItems(string query, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSelectItems(query, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item> CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService.EndSelectItems(System.IAsyncResult result) {
            return base.Channel.EndSelectItems(result);
        }
        
        private System.IAsyncResult OnBeginSelectItems(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string query = ((string)(inValues[0]));
            return ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService)(this)).BeginSelectItems(query, callback, asyncState);
        }
        
        private object[] OnEndSelectItems(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item> retVal = ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService)(this)).EndSelectItems(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSelectItemsCompleted(object state) {
            if ((this.SelectItemsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SelectItemsCompleted(this, new SelectItemsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SelectItemsAsync(string query) {
            this.SelectItemsAsync(query, null);
        }
        
        public void SelectItemsAsync(string query, object userState) {
            if ((this.onBeginSelectItemsDelegate == null)) {
                this.onBeginSelectItemsDelegate = new BeginOperationDelegate(this.OnBeginSelectItems);
            }
            if ((this.onEndSelectItemsDelegate == null)) {
                this.onEndSelectItemsDelegate = new EndOperationDelegate(this.OnEndSelectItems);
            }
            if ((this.onSelectItemsCompletedDelegate == null)) {
                this.onSelectItemsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSelectItemsCompleted);
            }
            base.InvokeAsync(this.onBeginSelectItemsDelegate, new object[] {
                        query}, this.onEndSelectItemsDelegate, this.onSelectItemsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService.BeginSelectSingleItem(string query, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSelectSingleItem(query, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService.EndSelectSingleItem(System.IAsyncResult result) {
            return base.Channel.EndSelectSingleItem(result);
        }
        
        private System.IAsyncResult OnBeginSelectSingleItem(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string query = ((string)(inValues[0]));
            return ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService)(this)).BeginSelectSingleItem(query, callback, asyncState);
        }
        
        private object[] OnEndSelectSingleItem(System.IAsyncResult result) {
            CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item retVal = ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService)(this)).EndSelectSingleItem(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSelectSingleItemCompleted(object state) {
            if ((this.SelectSingleItemCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SelectSingleItemCompleted(this, new SelectSingleItemCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SelectSingleItemAsync(string query) {
            this.SelectSingleItemAsync(query, null);
        }
        
        public void SelectSingleItemAsync(string query, object userState) {
            if ((this.onBeginSelectSingleItemDelegate == null)) {
                this.onBeginSelectSingleItemDelegate = new BeginOperationDelegate(this.OnBeginSelectSingleItem);
            }
            if ((this.onEndSelectSingleItemDelegate == null)) {
                this.onEndSelectSingleItemDelegate = new EndOperationDelegate(this.OnEndSelectSingleItem);
            }
            if ((this.onSelectSingleItemCompletedDelegate == null)) {
                this.onSelectSingleItemCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSelectSingleItemCompleted);
            }
            base.InvokeAsync(this.onBeginSelectSingleItemDelegate, new object[] {
                        query}, this.onEndSelectSingleItemDelegate, this.onSelectSingleItemCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService.BeginSelectItemsUsingXPath(string query, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSelectItemsUsingXPath(query, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item> CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService.EndSelectItemsUsingXPath(System.IAsyncResult result) {
            return base.Channel.EndSelectItemsUsingXPath(result);
        }
        
        private System.IAsyncResult OnBeginSelectItemsUsingXPath(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string query = ((string)(inValues[0]));
            return ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService)(this)).BeginSelectItemsUsingXPath(query, callback, asyncState);
        }
        
        private object[] OnEndSelectItemsUsingXPath(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item> retVal = ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService)(this)).EndSelectItemsUsingXPath(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSelectItemsUsingXPathCompleted(object state) {
            if ((this.SelectItemsUsingXPathCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SelectItemsUsingXPathCompleted(this, new SelectItemsUsingXPathCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SelectItemsUsingXPathAsync(string query) {
            this.SelectItemsUsingXPathAsync(query, null);
        }
        
        public void SelectItemsUsingXPathAsync(string query, object userState) {
            if ((this.onBeginSelectItemsUsingXPathDelegate == null)) {
                this.onBeginSelectItemsUsingXPathDelegate = new BeginOperationDelegate(this.OnBeginSelectItemsUsingXPath);
            }
            if ((this.onEndSelectItemsUsingXPathDelegate == null)) {
                this.onEndSelectItemsUsingXPathDelegate = new EndOperationDelegate(this.OnEndSelectItemsUsingXPath);
            }
            if ((this.onSelectItemsUsingXPathCompletedDelegate == null)) {
                this.onSelectItemsUsingXPathCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSelectItemsUsingXPathCompleted);
            }
            base.InvokeAsync(this.onBeginSelectItemsUsingXPathDelegate, new object[] {
                        query}, this.onEndSelectItemsUsingXPathDelegate, this.onSelectItemsUsingXPathCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService.BeginSelectSingleItemUsingXPath(string query, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSelectSingleItemUsingXPath(query, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService.EndSelectSingleItemUsingXPath(System.IAsyncResult result) {
            return base.Channel.EndSelectSingleItemUsingXPath(result);
        }
        
        private System.IAsyncResult OnBeginSelectSingleItemUsingXPath(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string query = ((string)(inValues[0]));
            return ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService)(this)).BeginSelectSingleItemUsingXPath(query, callback, asyncState);
        }
        
        private object[] OnEndSelectSingleItemUsingXPath(System.IAsyncResult result) {
            CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item retVal = ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService)(this)).EndSelectSingleItemUsingXPath(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSelectSingleItemUsingXPathCompleted(object state) {
            if ((this.SelectSingleItemUsingXPathCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SelectSingleItemUsingXPathCompleted(this, new SelectSingleItemUsingXPathCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SelectSingleItemUsingXPathAsync(string query) {
            this.SelectSingleItemUsingXPathAsync(query, null);
        }
        
        public void SelectSingleItemUsingXPathAsync(string query, object userState) {
            if ((this.onBeginSelectSingleItemUsingXPathDelegate == null)) {
                this.onBeginSelectSingleItemUsingXPathDelegate = new BeginOperationDelegate(this.OnBeginSelectSingleItemUsingXPath);
            }
            if ((this.onEndSelectSingleItemUsingXPathDelegate == null)) {
                this.onEndSelectSingleItemUsingXPathDelegate = new EndOperationDelegate(this.OnEndSelectSingleItemUsingXPath);
            }
            if ((this.onSelectSingleItemUsingXPathCompletedDelegate == null)) {
                this.onSelectSingleItemUsingXPathCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSelectSingleItemUsingXPathCompleted);
            }
            base.InvokeAsync(this.onBeginSelectSingleItemUsingXPathDelegate, new object[] {
                        query}, this.onEndSelectSingleItemUsingXPathDelegate, this.onSelectSingleItemUsingXPathCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService.BeginGetChildren(System.Guid parentItemId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetChildren(parentItemId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item> CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService.EndGetChildren(System.IAsyncResult result) {
            return base.Channel.EndGetChildren(result);
        }
        
        private System.IAsyncResult OnBeginGetChildren(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid parentItemId = ((System.Guid)(inValues[0]));
            return ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService)(this)).BeginGetChildren(parentItemId, callback, asyncState);
        }
        
        private object[] OnEndGetChildren(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item> retVal = ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService)(this)).EndGetChildren(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetChildrenCompleted(object state) {
            if ((this.GetChildrenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetChildrenCompleted(this, new GetChildrenCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetChildrenAsync(System.Guid parentItemId) {
            this.GetChildrenAsync(parentItemId, null);
        }
        
        public void GetChildrenAsync(System.Guid parentItemId, object userState) {
            if ((this.onBeginGetChildrenDelegate == null)) {
                this.onBeginGetChildrenDelegate = new BeginOperationDelegate(this.OnBeginGetChildren);
            }
            if ((this.onEndGetChildrenDelegate == null)) {
                this.onEndGetChildrenDelegate = new EndOperationDelegate(this.OnEndGetChildren);
            }
            if ((this.onGetChildrenCompletedDelegate == null)) {
                this.onGetChildrenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetChildrenCompleted);
            }
            base.InvokeAsync(this.onBeginGetChildrenDelegate, new object[] {
                        parentItemId}, this.onEndGetChildrenDelegate, this.onGetChildrenCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService.BeginCreateItem(System.Guid parentItemId, CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item newItem, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateItem(parentItemId, newItem, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService.EndCreateItem(System.IAsyncResult result) {
            return base.Channel.EndCreateItem(result);
        }
        
        private System.IAsyncResult OnBeginCreateItem(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid parentItemId = ((System.Guid)(inValues[0]));
            CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item newItem = ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item)(inValues[1]));
            return ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService)(this)).BeginCreateItem(parentItemId, newItem, callback, asyncState);
        }
        
        private object[] OnEndCreateItem(System.IAsyncResult result) {
            CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item retVal = ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService)(this)).EndCreateItem(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateItemCompleted(object state) {
            if ((this.CreateItemCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateItemCompleted(this, new CreateItemCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateItemAsync(System.Guid parentItemId, CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item newItem) {
            this.CreateItemAsync(parentItemId, newItem, null);
        }
        
        public void CreateItemAsync(System.Guid parentItemId, CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item newItem, object userState) {
            if ((this.onBeginCreateItemDelegate == null)) {
                this.onBeginCreateItemDelegate = new BeginOperationDelegate(this.OnBeginCreateItem);
            }
            if ((this.onEndCreateItemDelegate == null)) {
                this.onEndCreateItemDelegate = new EndOperationDelegate(this.OnEndCreateItem);
            }
            if ((this.onCreateItemCompletedDelegate == null)) {
                this.onCreateItemCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateItemCompleted);
            }
            base.InvokeAsync(this.onBeginCreateItemDelegate, new object[] {
                        parentItemId,
                        newItem}, this.onEndCreateItemDelegate, this.onCreateItemCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService.BeginUpdateItem(CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item item, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateItem(item, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService.EndUpdateItem(System.IAsyncResult result) {
            base.Channel.EndUpdateItem(result);
        }
        
        private System.IAsyncResult OnBeginUpdateItem(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item item = ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item)(inValues[0]));
            return ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService)(this)).BeginUpdateItem(item, callback, asyncState);
        }
        
        private object[] OnEndUpdateItem(System.IAsyncResult result) {
            ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService)(this)).EndUpdateItem(result);
            return null;
        }
        
        private void OnUpdateItemCompleted(object state) {
            if ((this.UpdateItemCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateItemCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateItemAsync(CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item item) {
            this.UpdateItemAsync(item, null);
        }
        
        public void UpdateItemAsync(CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item item, object userState) {
            if ((this.onBeginUpdateItemDelegate == null)) {
                this.onBeginUpdateItemDelegate = new BeginOperationDelegate(this.OnBeginUpdateItem);
            }
            if ((this.onEndUpdateItemDelegate == null)) {
                this.onEndUpdateItemDelegate = new EndOperationDelegate(this.OnEndUpdateItem);
            }
            if ((this.onUpdateItemCompletedDelegate == null)) {
                this.onUpdateItemCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateItemCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateItemDelegate, new object[] {
                        item}, this.onEndUpdateItemDelegate, this.onUpdateItemCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService.BeginDeleteItem(CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item item, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteItem(item, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService.EndDeleteItem(System.IAsyncResult result) {
            base.Channel.EndDeleteItem(result);
        }
        
        private System.IAsyncResult OnBeginDeleteItem(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item item = ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item)(inValues[0]));
            return ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService)(this)).BeginDeleteItem(item, callback, asyncState);
        }
        
        private object[] OnEndDeleteItem(System.IAsyncResult result) {
            ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService)(this)).EndDeleteItem(result);
            return null;
        }
        
        private void OnDeleteItemCompleted(object state) {
            if ((this.DeleteItemCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteItemCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteItemAsync(CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item item) {
            this.DeleteItemAsync(item, null);
        }
        
        public void DeleteItemAsync(CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item item, object userState) {
            if ((this.onBeginDeleteItemDelegate == null)) {
                this.onBeginDeleteItemDelegate = new BeginOperationDelegate(this.OnBeginDeleteItem);
            }
            if ((this.onEndDeleteItemDelegate == null)) {
                this.onEndDeleteItemDelegate = new EndOperationDelegate(this.OnEndDeleteItem);
            }
            if ((this.onDeleteItemCompletedDelegate == null)) {
                this.onDeleteItemCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteItemCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteItemDelegate, new object[] {
                        item}, this.onEndDeleteItemDelegate, this.onDeleteItemCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService.BeginGetFixedPaths(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetFixedPaths(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.FixedPaths CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService.EndGetFixedPaths(System.IAsyncResult result) {
            return base.Channel.EndGetFixedPaths(result);
        }
        
        private System.IAsyncResult OnBeginGetFixedPaths(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService)(this)).BeginGetFixedPaths(callback, asyncState);
        }
        
        private object[] OnEndGetFixedPaths(System.IAsyncResult result) {
            CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.FixedPaths retVal = ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService)(this)).EndGetFixedPaths(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetFixedPathsCompleted(object state) {
            if ((this.GetFixedPathsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetFixedPathsCompleted(this, new GetFixedPathsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetFixedPathsAsync() {
            this.GetFixedPathsAsync(null);
        }
        
        public void GetFixedPathsAsync(object userState) {
            if ((this.onBeginGetFixedPathsDelegate == null)) {
                this.onBeginGetFixedPathsDelegate = new BeginOperationDelegate(this.OnBeginGetFixedPaths);
            }
            if ((this.onEndGetFixedPathsDelegate == null)) {
                this.onEndGetFixedPathsDelegate = new EndOperationDelegate(this.OnEndGetFixedPaths);
            }
            if ((this.onGetFixedPathsCompletedDelegate == null)) {
                this.onGetFixedPathsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetFixedPathsCompleted);
            }
            base.InvokeAsync(this.onBeginGetFixedPathsDelegate, null, this.onEndGetFixedPathsDelegate, this.onGetFixedPathsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService.BeginRefreshFeed(CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Feed feed, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRefreshFeed(feed, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService.EndRefreshFeed(System.IAsyncResult result) {
            base.Channel.EndRefreshFeed(result);
        }
        
        private System.IAsyncResult OnBeginRefreshFeed(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Feed feed = ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Feed)(inValues[0]));
            return ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService)(this)).BeginRefreshFeed(feed, callback, asyncState);
        }
        
        private object[] OnEndRefreshFeed(System.IAsyncResult result) {
            ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService)(this)).EndRefreshFeed(result);
            return null;
        }
        
        private void OnRefreshFeedCompleted(object state) {
            if ((this.RefreshFeedCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RefreshFeedCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RefreshFeedAsync(CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Feed feed) {
            this.RefreshFeedAsync(feed, null);
        }
        
        public void RefreshFeedAsync(CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Feed feed, object userState) {
            if ((this.onBeginRefreshFeedDelegate == null)) {
                this.onBeginRefreshFeedDelegate = new BeginOperationDelegate(this.OnBeginRefreshFeed);
            }
            if ((this.onEndRefreshFeedDelegate == null)) {
                this.onEndRefreshFeedDelegate = new EndOperationDelegate(this.OnEndRefreshFeed);
            }
            if ((this.onRefreshFeedCompletedDelegate == null)) {
                this.onRefreshFeedCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRefreshFeedCompleted);
            }
            base.InvokeAsync(this.onBeginRefreshFeedDelegate, new object[] {
                        feed}, this.onEndRefreshFeedDelegate, this.onRefreshFeedCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService CreateChannel() {
            return new SitecoreServiceClientChannel(this);
        }
        
        private class SitecoreServiceClientChannel : ChannelBase<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService>, CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService {
            
            public SitecoreServiceClientChannel(System.ServiceModel.ClientBase<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.SitecoreService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetItemById(System.Guid itemId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = itemId;
                System.IAsyncResult _result = base.BeginInvoke("GetItemById", _args, callback, asyncState);
                return _result;
            }
            
            public CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item EndGetItemById(System.IAsyncResult result) {
                object[] _args = new object[0];
                CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item _result = ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item)(base.EndInvoke("GetItemById", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetItemByPath(string itemPath, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = itemPath;
                System.IAsyncResult _result = base.BeginInvoke("GetItemByPath", _args, callback, asyncState);
                return _result;
            }
            
            public CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item EndGetItemByPath(System.IAsyncResult result) {
                object[] _args = new object[0];
                CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item _result = ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item)(base.EndInvoke("GetItemByPath", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetRootItem(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetRootItem", _args, callback, asyncState);
                return _result;
            }
            
            public CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item EndGetRootItem(System.IAsyncResult result) {
                object[] _args = new object[0];
                CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item _result = ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item)(base.EndInvoke("GetRootItem", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetItemsByIds(System.Collections.ObjectModel.ObservableCollection<System.Guid> itemIds, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = itemIds;
                System.IAsyncResult _result = base.BeginInvoke("GetItemsByIds", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item> EndGetItemsByIds(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item> _result = ((System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item>)(base.EndInvoke("GetItemsByIds", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSelectItems(string query, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = query;
                System.IAsyncResult _result = base.BeginInvoke("SelectItems", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item> EndSelectItems(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item> _result = ((System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item>)(base.EndInvoke("SelectItems", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSelectSingleItem(string query, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = query;
                System.IAsyncResult _result = base.BeginInvoke("SelectSingleItem", _args, callback, asyncState);
                return _result;
            }
            
            public CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item EndSelectSingleItem(System.IAsyncResult result) {
                object[] _args = new object[0];
                CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item _result = ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item)(base.EndInvoke("SelectSingleItem", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSelectItemsUsingXPath(string query, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = query;
                System.IAsyncResult _result = base.BeginInvoke("SelectItemsUsingXPath", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item> EndSelectItemsUsingXPath(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item> _result = ((System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item>)(base.EndInvoke("SelectItemsUsingXPath", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSelectSingleItemUsingXPath(string query, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = query;
                System.IAsyncResult _result = base.BeginInvoke("SelectSingleItemUsingXPath", _args, callback, asyncState);
                return _result;
            }
            
            public CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item EndSelectSingleItemUsingXPath(System.IAsyncResult result) {
                object[] _args = new object[0];
                CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item _result = ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item)(base.EndInvoke("SelectSingleItemUsingXPath", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetChildren(System.Guid parentItemId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = parentItemId;
                System.IAsyncResult _result = base.BeginInvoke("GetChildren", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item> EndGetChildren(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item> _result = ((System.Collections.ObjectModel.ObservableCollection<CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item>)(base.EndInvoke("GetChildren", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCreateItem(System.Guid parentItemId, CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item newItem, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = parentItemId;
                _args[1] = newItem;
                System.IAsyncResult _result = base.BeginInvoke("CreateItem", _args, callback, asyncState);
                return _result;
            }
            
            public CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item EndCreateItem(System.IAsyncResult result) {
                object[] _args = new object[0];
                CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item _result = ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item)(base.EndInvoke("CreateItem", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdateItem(CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item item, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = item;
                System.IAsyncResult _result = base.BeginInvoke("UpdateItem", _args, callback, asyncState);
                return _result;
            }
            
            public void EndUpdateItem(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("UpdateItem", _args, result);
            }
            
            public System.IAsyncResult BeginDeleteItem(CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Item item, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = item;
                System.IAsyncResult _result = base.BeginInvoke("DeleteItem", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDeleteItem(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DeleteItem", _args, result);
            }
            
            public System.IAsyncResult BeginGetFixedPaths(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetFixedPaths", _args, callback, asyncState);
                return _result;
            }
            
            public CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.FixedPaths EndGetFixedPaths(System.IAsyncResult result) {
                object[] _args = new object[0];
                CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.FixedPaths _result = ((CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.FixedPaths)(base.EndInvoke("GetFixedPaths", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRefreshFeed(CompiledDomainModel.Demo.SLFeedReader.FeedReaderService.Feed feed, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = feed;
                System.IAsyncResult _result = base.BeginInvoke("RefreshFeed", _args, callback, asyncState);
                return _result;
            }
            
            public void EndRefreshFeed(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("RefreshFeed", _args, result);
            }
        }
    }
}
